project:
  type: website

website:
  title: "Open Educational Resources with Quarto"
  reader-mode: true
  comments:
    hypothesis: true
    giscus:
      repo: mdlama/oerquarto
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: start.qmd
        text: "Getting Started"
      - href: authoring.qmd
        text: "Authoring"
      - section: "Code and Extensions"
        contents:
          - authoring_code.qmd
          - extensions.qmd
      - section: "Interactive Documents"
        contents:
          - interactives.qmd
          - quarto_live.qmd
          - shinylive.qmd
      - href: publishing.qmd
        text: "Publishing"
      - href: slides.qmd
        text: "Slides"
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    lightbox: auto
    df-print: paged
    code-tools: true
    css: styles.css
    toc: true
  live-html:
    theme:
      light: flatly
      dark: darkly
    lightbox: auto
    df-print: paged
    css: styles.css
    toc: true