---
title: "Authoring"
format:
  html:
    axe: true
---

This page builds off of the [Authoring](https://quarto.org/docs/get-started/authoring/rstudio.html) tutorial on the Quarto website.

# Multiple formats

Creating multiple document formats can be very useful in an educational context. Multiple document formats is [introduced in the Authoring tutorial](https://quarto.org/docs/get-started/authoring/rstudio.html#multiple-formats).

This is a particularly useful feature when rendering to HTML documents, allowing you to create multiple versions of the same document, each with a different output format. For example, you could create an HTML version for web viewing and a PDF or DOCX version for students to download. You can find a more advanced discussion about this feature in the [Quarto documentation](https://quarto.org/docs/output-formats/html-multi-format.html).

## Combining dynamic and static content

How do you handle multiple formats when your resource includes dynamic content, such as [HTMLWidgets](https://quarto.org/docs/interactive/widgets/htmlwidgets.html), [interactives](https://quarto.org/docs/interactive/), or [live code blocks](https://r-wasm.github.io/quarto-live/)? Quarto has an advanced feature called [Conditional Content](https://quarto.org/docs/authoring/conditional.html) that allows you to specify which content to include based on the output type. For example, dynamic content will only show in the HTML output, while the static output formats like PDF and Microsoft Word can either not include the dynamic content or have different content.

# Accessibility

Many institutions are implenting stricter accessibility requirements for teaching resources.

 - [HTML Accessibility Checks](https://quarto.org/docs/output-formats/html-accessibility.html)
 - [PDF Accessibility Standards](https://quarto.org/docs/output-formats/pdf-basics.html#pdf-accessibility-standards)
